import dotenv from "dotenv";
import { supabase } from "../supabase"; // supabase tables
import { v4 as uuidv4 } from "uuid"; // generating uuids
import { cosineSimilarity } from "./similarity"; // vector comparisons
import { getMCAnswer } from "./multipleChoiceMap"; // multiple choice answers
import { embedText, EMBEDDING_DIM } from "./embedder"; // local sentence-transformers embeddings

dotenv.config();

interface Participant {
  // Primary key in form_responses
  id: string;
  // Basic info
  email: string;
  name: string;
  pronouns: string;
  program: string; // used for vector embedding
  year: string; // used for vector embedding
  social_media_links: string;
  // Open-ended responses
  // Career
  career: string; // used for vector embedding
  // Friendship
  friend_traits: string; // used for vector embedding
  self_desc: string; // used for vector embedding
  goal: string; // used for vector embedding
  // Interests
  fun: string; // used for vector embedding
  music: string; // used for vector embedding
  // Multiple choice: [a, b, c, d, e]
  class_seat: "a" | "b" | "c" | "d" | "e"; // used for vector embedding
  evil_hobby: "a" | "b" | "c" | "d" | "e"; // used for vector embedding
  most_likely_to: "a" | "b" | "c" | "d" | "e"; // used for vector embedding
  caught_watching: "a" | "b" | "c" | "d" | "e"; // used for vector embedding
  // Vector embedding for participant, generated by a local sentence-transformers model.
  vector_embedding?: number[];
}

interface Match {
  id?: string; // UUID primary key (auto-generated)
  person1_id: string; // UUID FK to form_responses.id
  person2_id: string; // UUID FK to form_responses.id
  similarity_score: number; // cosine similarity
  emoji: string; // hex for generated emoji
}

// HARD-CODED odd participant to be pushed to form_responses if there is an odd number of participants.
// Each term, change the NAME of the participant to some exec who is going to be at the event.
// They will be matched with the (2k+1)th person.
const oddId = uuidv4();
const odd_participant: Participant = {
  id: oddId,
  email: "j236xu@uwaterloo.ca",
  name: "Jocelyn Xu",
  pronouns: "She/Her",
  program: "CS", // used for vector embedding
  year: "2B", // used for vector embedding
  social_media_links: "https://www.linkedin.com/in/jocelyn-xu-xt/",
  career: "Ideally quant, currently SWE. ", // used for vector embedding
  friend_traits: "A calm and respectful friend. ", // used for vector embedding
  self_desc: "Peculiar. ", // used for vector embedding
  goal: "To play chess with someone. ", // used for vector embedding
  fun: "Play chess, osu. ", // used for vector embedding
  music: "Lana Del Rey. ", // used for vector embedding
  class_seat: "e", // used for vector embedding
  evil_hobby: "c", // used for vector embedding
  most_likely_to: "a", // used for vector embedding
  caught_watching: "a", // used for vector embedding
  // No hard-coded vector needed; computed like any other participant since embeddings are now free.
};

/**
 * Deletes all rows from curr_matches table.
 */
export async function clearCurrMatchesTable() {
  const { error } = await supabase.from("curr_matches").delete().not("person1_id", "is", null); // delete every row where person1_id is not null

  if (error) {
    console.error("Failed to clear curr_matches table:", error);
    process.exit(1);
  }

  console.log("Deleted all rows from curr_matches table.");
}

/**
 * FETCHES EVERY ROW OF form_responses.
 * IF THE vector_embeddings COLUMN IS NOT ALREADY POPULATED WITH A VALID numeric[],
 * GENERATE THE VECTOR EMBEDDING USING A LOCAL sentence-transformers MODEL.
 * IF THERE IS AN ODD NUMBER OF PEOPLE, PUSH odd_participant TO THE TABLE IF NOT ALREADY THERE.
 */
export async function updateFormResponsesTableWithVectorEmbeddings() {
  // fetch every row
  const { data: rows, error: fetchErr } = await supabase.from("form_responses").select("*");
  if (fetchErr) throw fetchErr;
  if (!rows) return;

  for (const row of rows) {
    // for each row, build participant structure

    // Skip only if the embedding is present and matches the current model's dimension (stale-model vectors get regenerated).
    if (row.vector_embedding && row.vector_embedding.length === EMBEDDING_DIM) {
      console.log(`Vector for ${row.id} already exists, skipping.`);
      continue;
    }

    const p: Participant = {
      ...row,
      class_seat: row.class_seat,
      evil_hobby: row.evil_hobby,
      most_likely_to: row.most_likely_to,
      caught_watching: row.caught_watching,
    };

    const textForEmbed = [
      // concatenate everything for embedding input
      p.program,
      p.year,
      p.career,
      p.friend_traits,
      p.self_desc,
      p.goal,
      p.fun,
      p.music,
      getMCAnswer("class_seat", p.class_seat), // turned MC answer [a, b, c, d, e] into its string response
      getMCAnswer("evil_hobby", p.evil_hobby),
      getMCAnswer("most_likely_to", p.most_likely_to),
      getMCAnswer("caught_watching", p.caught_watching),
    ].join(" • "); // separator for each field

    const vector = await embedText(textForEmbed); // create vector embedding locally

    const { error: updErr } = await supabase
      .from("form_responses")
      .update({ vector_embedding: vector }) // insert into supabase the vector_embedding
      .eq("id", p.id);

    if (updErr) {
      console.error(`Failed to update embedding for ${p.id}:`, updErr);
    } else {
      console.log(`Updated embedding for ${p.id}`);
    }
  }
}

/**
 * If the array has odd length:
 * - If the odd_participant is there, remove them to make the length even.
 * - If the odd_participant is not there, add them to make the length even.
 */
export async function handleOddParticipant(participants: { id: string }[]) {
  const oddParticipantExists = participants.some((p) => p.id === odd_participant.id);

  if (participants.length % 2 === 1 && !oddParticipantExists) {
    // odd number of people, and haven't inserted the hard-coded value yet.
    await supabase.from("form_responses").insert([odd_participant]); // insert the hard-coded odd_participant.
    console.log(
      "There is an odd number of people, not including odd_participant. Added them to form_responses. ",
    );
  } else if (participants.length % 2 === 1 && oddParticipantExists) {
    // odd number of people, and hard-coded odd_participant is one of them.
    await supabase
      .from("form_responses")
      .delete() // remove the hard-coded odd_participant.
      .eq("id", odd_participant.id);
    console.log(
      "There is an odd number of people, including odd_participant. Removed them from form_responses. ",
    );
  } else {
    // no action needed, print helpful message.
    console.log("There is an even number of people. No parity-related handling is required. ");
  }
}

/**
 * ASSUMES EVERY ROW IN form_responses HAS A VALID vector_embedding ENCODED AS A numeric[].
 * ASSUMES THERE IS AN EVEN NUMBER OF PARTICIPANTS IN form_responses, AS HANDLED BY handleOddParticipant.
 * ASSUMES THE curr_matches TABLE IS EMPTY, AS HANDLED BY clearCurrMatchesTable.
 * RUNS cosineSimilarity[] TO GATHER THE CLOSEST VECTOR PAIRS, MATCHING THEM WITH GREEDY ALGORITHM.
 * RETURNS ARRAY OF Match TO BE INSERTED INTO curr_matches TABLE and the previous_matches TABLE.
 */
/**
 * ASSUMES EVERY ROW IN form_responses HAS A VALID vector_embedding ENCODED AS A numeric[].
 * ASSUMES THERE IS AN EVEN NUMBER OF PARTICIPANTS IN form_responses, AS HANDLED BY handleOddParticipant.
 * ASSUMES THE curr_matches TABLE IS EMPTY, AS HANDLED BY clearCurrMatchesTable.
 * RUNS cosineSimilarity[] TO GATHER THE CLOSEST VECTOR PAIRS, MATCHING THEM WITH GREEDY ALGORITHM.
 * EXCLUDES PAIRS WHO HAVE ALREADY BEEN MATCHED IN previous_matches TABLE.
 * PRIORITIZES MATCHING BASED ON GENDER INTENTION (0=same, 1=opposite, 2=both).
 * RETURNS ARRAY OF Match TO BE INSERTED INTO curr_matches TABLE and the previous_matches TABLE.
 */
export async function matchParticipants(): Promise<Match[]> {
  // fetch everyone's id + embedding + gender + intention
  const { data: rows, error: fetchErr } = await supabase
    .from("form_responses")
    .select("id, email, vector_embedding, pronouns, intention");
  if (fetchErr) {
    console.error("Could not fetch embeddings:", fetchErr);
    throw fetchErr;
  }
  if (!rows) return [];

  // Helper function to determine gender from pronouns
  function getGender(pronouns: string): "male" | "female" | "other" {
    const p = pronouns.toLowerCase();
    if (p.includes("he/him")) return "male";
    if (p.includes("she/her")) return "female";
    return "other";
  }

  type ParticipantRow = {
    id: string;
    email: string;
    vector_embedding: number[];
    pronouns: string;
    intention: number;
  };

  // Helper function to check if two people's intentions are compatible
  function areIntentionsCompatible(person1: ParticipantRow, person2: ParticipantRow): boolean {
    const gender1 = getGender(person1.pronouns);
    const gender2 = getGender(person2.pronouns);

    // Check person1's intention
    const person1Compatible =
      person1.intention === 2 || // both genders
      (person1.intention === 0 && gender1 === gender2) || // same gender
      (person1.intention === 1 && gender1 !== gender2); // opposite gender

    // Check person2's intention
    const person2Compatible =
      person2.intention === 2 || // both genders
      (person2.intention === 0 && gender1 === gender2) || // same gender
      (person2.intention === 1 && gender1 !== gender2); // opposite gender

    // Both must be compatible with each other
    return person1Compatible && person2Compatible;
  }

  // build all pairwise similarities
  type Pair = { i: number; j: number; sim: number; intentionMatch: boolean };
  const pairs: Pair[] = [];
  for (let i = 0; i < rows.length; i++) {
    const vi = rows[i].vector_embedding!;
    for (let j = i + 1; j < rows.length; j++) {
      const vj = rows[j].vector_embedding!;
      const intentionMatch = areIntentionsCompatible(rows[i], rows[j]);
      pairs.push({
        i,
        j,
        sim: cosineSimilarity(vi, vj),
        intentionMatch,
      });
    }
  }

  // Fetch already matched pairs from previous_matches table
  const { data: already_matched, error: prevErr } = await supabase
    .from("previous_matches")
    .select("person1_id, person2_id");
  if (prevErr) {
    console.error("Could not fetch previous_matches:", prevErr);
    throw prevErr;
  }

  // map each participant → set of UUIDs they've already been matched with
  const prevMap = new Map<string, Set<string>>();
  for (const { person1_id, person2_id } of already_matched || []) {
    if (!prevMap.has(person1_id)) {
      prevMap.set(person1_id, new Set());
    }
    if (!prevMap.has(person2_id)) {
      prevMap.set(person2_id, new Set());
    }
    prevMap.get(person1_id)!.add(person2_id);
    prevMap.get(person2_id)!.add(person1_id);
  }

  console.log(`Found ${already_matched?.length || 0} previous matches to exclude.`);

  // Separate pairs into intention-compatible and intention-incompatible
  const intentionPairs = pairs.filter((p) => p.intentionMatch);
  const nonIntentionPairs = pairs.filter((p) => !p.intentionMatch);

  // Sort both by similarity (descending)
  intentionPairs.sort((a, b) => b.sim - a.sim);
  nonIntentionPairs.sort((a, b) => b.sim - a.sim);

  console.log(
    `Total pairs: ${pairs.length}, Intention-compatible: ${intentionPairs.length}, Non-compatible: ${nonIntentionPairs.length}`,
  );

  // Track who has been matched
  const used = new Set<number>();
  const matches: Match[] = [];

  // PHASE 1: Match intention-compatible pairs first (greedy by similarity)
  console.log("\n=== PHASE 1: Matching intention-compatible pairs ===");
  for (const { i, j, sim } of intentionPairs) {
    const id1 = rows[i].id,
      id2 = rows[j].id;

    // skip if either is already in a new match
    if (used.has(i) || used.has(j)) continue;

    // skip if they've met before (check both directions)
    const met1 = prevMap.get(id1)?.has(id2) ?? false;
    const met2 = prevMap.get(id2)?.has(id1) ?? false;
    if (met1 || met2) {
      console.log(
        `Skipping pair (${rows[i].email}, ${rows[j].email}) - already matched before`,
      );
      continue;
    }

    // take this pair
    used.add(i);
    used.add(j);
    matches.push({
      person1_id: id1,
      person2_id: id2,
      similarity_score: sim,
      emoji: "",
    });

    const gender1 = getGender(rows[i].pronouns);
    const gender2 = getGender(rows[j].pronouns);
    console.log(
      `✓ Matched (INTENTION): ${rows[i].email} [${gender1}, pref=${
        rows[i].intention
      }] ↔ ${rows[j].email} [${gender2}, pref=${rows[j].intention}] (sim: ${sim.toFixed(4)})`,
    );

    if (used.size === rows.length) break;
  }

  console.log(
    `\nPhase 1 complete: ${matches.length} matches, ${used.size}/${rows.length} participants matched`,
  );

  // PHASE 2: Match remaining participants by similarity only (ignoring intention)
  if (used.size < rows.length) {
    console.log("\n=== PHASE 2: Matching remaining participants (ignoring intention) ===");
    for (const { i, j, sim } of nonIntentionPairs) {
      const id1 = rows[i].id,
        id2 = rows[j].id;

      // skip if either is already in a new match
      if (used.has(i) || used.has(j)) continue;

      // skip if they've met before
      const met1 = prevMap.get(id1)?.has(id2) ?? false;
      const met2 = prevMap.get(id2)?.has(id1) ?? false;
      if (met1 || met2) {
        console.log(
          `Skipping pair (${rows[i].email}, ${rows[j].email}) - already matched before`,
        );
        continue;
      }

      // take this pair
      used.add(i);
      used.add(j);
      matches.push({
        person1_id: id1,
        person2_id: id2,
        similarity_score: sim,
        emoji: "",
      });

      const gender1 = getGender(rows[i].pronouns);
      const gender2 = getGender(rows[j].pronouns);
      console.log(
        `○ Matched (FALLBACK): ${rows[i].email} [${gender1}, pref=${
          rows[i].intention
        }] ↔ ${rows[j].email} [${gender2}, pref=${rows[j].intention}] (sim: ${sim.toFixed(4)})`,
      );

      if (used.size === rows.length) break;
    }
  }

  console.log(`\n=== MATCHING COMPLETE ===`);
  console.log(`Total matches: ${matches.length}`);
  console.log(`Participants matched: ${used.size}/${rows.length}`);

  if (used.size < rows.length) {
    console.warn(`WARNING: ${rows.length - used.size} participants could not be matched!`);
    const unmatchedIndices = Array.from({ length: rows.length }, (_, i) => i).filter(
      (i) => !used.has(i),
    );
    unmatchedIndices.forEach((i) => {
      console.warn(
        `  - ${rows[i].email} [${getGender(rows[i].pronouns)}, pref=${rows[i].intention}]`,
      );
    });
  }

  return matches;
}
// export async function matchParticipants(): Promise<Match[]> {
//   // fetch everyone's id + embedding
//   const { data: rows, error: fetchErr } = await supabase
//     .from('form_responses')
//     .select('id, email, vector_embedding');
//   if (fetchErr) {
//     console.error('Could not fetch embeddings:', fetchErr);
//     throw fetchErr;
//   }
//   if (!rows) return [];

//   // build all pairwise similarities
//   type Pair = { i: number; j: number; sim: number };
//   const pairs: Pair[] = [];
//   for (let i = 0; i < rows.length; i++) {
//     const vi = rows[i].vector_embedding!;
//     for (let j = i + 1; j < rows.length; j++) {
//       const vj = rows[j].vector_embedding!;
//       pairs.push({ i, j, sim: cosineSimilarity(vi, vj) });
//     }
//   }

//   // determine already_matched array from curr_matches table
//   const { data: already_matched, error: currErr } = await supabase
//     .from('curr_matches')
//     .select('person1_id, person2_id'); // get the person1_id and person2_id
//   if (currErr) throw currErr;

//   // map each participant → set of UUIDs they've already been matched with
//   const prevMap = new Map<string, Set<string>>();
//   for (const { person1_id, person2_id } of already_matched || []) {
//     if (!prevMap.has(person1_id)) {
//       prevMap.set(person1_id, new Set());
//     }
//     if (!prevMap.has(person2_id)) {
//       prevMap.set(person2_id, new Set());
//     }
//     prevMap.get(person1_id)!.add(person2_id);
//     prevMap.get(person2_id)!.add(person1_id);
//   }

//   // greedy match: pick best pairs without reusing any participant
//   const used = new Set<number>();
//   const matches: Match[] = [];

//   pairs.sort((a, b) => b.sim - a.sim); // sort descending by similarity

//   for (const { i, j, sim } of pairs) { // for each pair and similarity
//     const id1 = rows[i].id, id2 = rows[j].id;

//     // skip if either is already in a new match
//     if (used.has(i) || used.has(j)) continue;

//     // skip if they've met before
//     const met1 = prevMap.get(id1)?.has(id2) ?? false;
//     const met2 = prevMap.get(id2)?.has(id1) ?? false;
//     if (met1 || met2) continue;

//     // otherwise take this pair
//     used.add(i);
//     used.add(j);
//     matches.push({ person1_id: rows[i].id, person2_id: rows[j].id, similarity_score: sim, emoji: '' });

//     if (used.size === rows.length) break;
//   }

//   // return the array of Match
//   return matches;
// }

// TAKES AN ARRAY Match[] AND UPDATES curr_matches WITH EACH ENTRY.
// curr_matches TABLE MATCHES EXACTLY THE STRUCTURE OF Match: person1_id (uuid), person2_id (uuid), similarity_score (float8), emoji (text).
export async function updateCurrMatches(matches: Match[]): Promise<Match[]> {
  if (matches.length === 0) {
    // Print helpful log message if matches: Match[] is an empty array.
    console.log("No matches to insert into curr_matches.");
    return [];
  }

  const { data, error } = await supabase
    .from("curr_matches")
    .insert(matches) // insert all matches into the table curr_matches.
    .select("*");

  if (error) {
    // catch error if occurred.
    console.error("Failed to update curr_matches:", error);
    throw error;
  }

  console.log(`Inserted ${data?.length ?? 0} matches into curr_matches.`);
  return data ?? [];
}

/**
 * Helper: inserts or appends a single side of a match into previous_matches.
 */
async function updatePreviousMatchesForParty(
  ownerId: string,
  partnerId: string,
  similarity_score: number,
  emoji: string,
): Promise<void> {
  // Check if this match already exists (either direction)
  const { data: existingMatch1, error: checkErr1 } = await supabase
    .from("previous_matches")
    .select("*")
    .eq("person1_id", ownerId)
    .eq("person2_id", partnerId)
    .maybeSingle();

  const { data: existingMatch2, error: checkErr2 } = await supabase
    .from("previous_matches")
    .select("*")
    .eq("person1_id", partnerId)
    .eq("person2_id", ownerId)
    .maybeSingle();

  if (checkErr1 || checkErr2) {
    console.error("Error checking existing match for", ownerId, checkErr1 || checkErr2);
    return;
  }

  if (!existingMatch1 && !existingMatch2) {
    // no existing match: insert new
    const { error: insertErr } = await supabase.from("previous_matches").insert([
      {
        person1_id: ownerId,
        person2_id: partnerId,
        similarity_score: similarity_score,
        emoji: emoji,
      },
    ]);
    if (insertErr) {
      console.error("Error inserting previous_matches for", ownerId, insertErr);
    } else {
      console.log("Created previous_matches row for", ownerId);
    }
  } else {
    console.log("Match already exists in previous_matches for", ownerId, "and", partnerId);
  }
}

// TAKES AN ARRAY Match[] AND APPENDS THE UUID Match.person2_id TO Match.person1_id's ROW.
// ALSO APPENDS THE Match.similarity_score TO THE similarity_scores[] OF Match.person1_id's ROW,
// AND THE Match.emoji TO THE emojis[] OF Match.person1_id's ROW.
// IF ROW FOR Match.person1_id DOES NOT ALREADY EXIST, CREATES A ROW.
// REPEATS THIS PERSON FOR ALL Match.person2_id's (since a Match is a pair, we need to account for both parties of the pair).
export async function updatePreviousMatches(matches: Match[]): Promise<void> {
  if (matches.length === 0) {
    console.log("No matches to update in previous_matches.");
    return;
  }

  for (const m of matches) {
    const { person1_id, person2_id, similarity_score, emoji } = m;

    // update for both sides (but only insert once to avoid duplicates)
    await updatePreviousMatchesForParty(person1_id, person2_id, similarity_score, emoji);
  }
}
